/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUpcomingRouteImport } from './routes/_authenticated/upcoming'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPredictionsRouteImport } from './routes/_authenticated/predictions'
import { Route as AuthenticatedPoolsRouteImport } from './routes/_authenticated/pools'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedH2hRouteImport } from './routes/_authenticated/h2h'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPoolsPoolIdRouteImport } from './routes/_authenticated/pools.$poolId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCronRefreshFixturesRouteImport } from './routes/api/public/cron/refresh-fixtures'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpcomingRoute = AuthenticatedUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPredictionsRoute =
  AuthenticatedPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoolsRoute = AuthenticatedPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedH2hRoute = AuthenticatedH2hRouteImport.update({
  id: '/h2h',
  path: '/h2h',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoolsPoolIdRoute =
  AuthenticatedPoolsPoolIdRouteImport.update({
    id: '/$poolId',
    path: '/$poolId',
    getParentRoute: () => AuthenticatedPoolsRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRefreshFixturesRoute =
  ApiPublicCronRefreshFixturesRouteImport.update({
    id: '/api/public/cron/refresh-fixtures',
    path: '/api/public/cron/refresh-fixtures',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/h2h': typeof AuthenticatedH2hRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import': typeof AuthenticatedImportRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/live': typeof AuthenticatedLiveRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/pools': typeof AuthenticatedPoolsRouteWithChildren
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/upcoming': typeof AuthenticatedUpcomingRoute
  '/pools/$poolId': typeof AuthenticatedPoolsPoolIdRoute
  '/api/public/cron/refresh-fixtures': typeof ApiPublicCronRefreshFixturesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/h2h': typeof AuthenticatedH2hRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import': typeof AuthenticatedImportRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/live': typeof AuthenticatedLiveRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/pools': typeof AuthenticatedPoolsRouteWithChildren
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/upcoming': typeof AuthenticatedUpcomingRoute
  '/pools/$poolId': typeof AuthenticatedPoolsPoolIdRoute
  '/api/public/cron/refresh-fixtures': typeof ApiPublicCronRefreshFixturesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/h2h': typeof AuthenticatedH2hRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/pools': typeof AuthenticatedPoolsRouteWithChildren
  '/_authenticated/predictions': typeof AuthenticatedPredictionsRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/upcoming': typeof AuthenticatedUpcomingRoute
  '/_authenticated/pools/$poolId': typeof AuthenticatedPoolsPoolIdRoute
  '/api/public/cron/refresh-fixtures': typeof ApiPublicCronRefreshFixturesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/h2h'
    | '/history'
    | '/import'
    | '/leaderboard'
    | '/live'
    | '/matches'
    | '/pools'
    | '/predictions'
    | '/pricing'
    | '/teams'
    | '/upcoming'
    | '/pools/$poolId'
    | '/api/public/cron/refresh-fixtures'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/h2h'
    | '/history'
    | '/import'
    | '/leaderboard'
    | '/live'
    | '/matches'
    | '/pools'
    | '/predictions'
    | '/pricing'
    | '/teams'
    | '/upcoming'
    | '/pools/$poolId'
    | '/api/public/cron/refresh-fixtures'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/h2h'
    | '/_authenticated/history'
    | '/_authenticated/import'
    | '/_authenticated/leaderboard'
    | '/_authenticated/live'
    | '/_authenticated/matches'
    | '/_authenticated/pools'
    | '/_authenticated/predictions'
    | '/_authenticated/pricing'
    | '/_authenticated/teams'
    | '/_authenticated/upcoming'
    | '/_authenticated/pools/$poolId'
    | '/api/public/cron/refresh-fixtures'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronRefreshFixturesRoute: typeof ApiPublicCronRefreshFixturesRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upcoming': {
      id: '/_authenticated/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof AuthenticatedUpcomingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/predictions': {
      id: '/_authenticated/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AuthenticatedPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pools': {
      id: '/_authenticated/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof AuthenticatedPoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/h2h': {
      id: '/_authenticated/h2h'
      path: '/h2h'
      fullPath: '/h2h'
      preLoaderRoute: typeof AuthenticatedH2hRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pools/$poolId': {
      id: '/_authenticated/pools/$poolId'
      path: '/$poolId'
      fullPath: '/pools/$poolId'
      preLoaderRoute: typeof AuthenticatedPoolsPoolIdRouteImport
      parentRoute: typeof AuthenticatedPoolsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-fixtures': {
      id: '/api/public/cron/refresh-fixtures'
      path: '/api/public/cron/refresh-fixtures'
      fullPath: '/api/public/cron/refresh-fixtures'
      preLoaderRoute: typeof ApiPublicCronRefreshFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPoolsRouteChildren {
  AuthenticatedPoolsPoolIdRoute: typeof AuthenticatedPoolsPoolIdRoute
}

const AuthenticatedPoolsRouteChildren: AuthenticatedPoolsRouteChildren = {
  AuthenticatedPoolsPoolIdRoute: AuthenticatedPoolsPoolIdRoute,
}

const AuthenticatedPoolsRouteWithChildren =
  AuthenticatedPoolsRoute._addFileChildren(AuthenticatedPoolsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedH2hRoute: typeof AuthenticatedH2hRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedPoolsRoute: typeof AuthenticatedPoolsRouteWithChildren
  AuthenticatedPredictionsRoute: typeof AuthenticatedPredictionsRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedUpcomingRoute: typeof AuthenticatedUpcomingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedH2hRoute: AuthenticatedH2hRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedPoolsRoute: AuthenticatedPoolsRouteWithChildren,
  AuthenticatedPredictionsRoute: AuthenticatedPredictionsRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedUpcomingRoute: AuthenticatedUpcomingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronRefreshFixturesRoute: ApiPublicCronRefreshFixturesRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
