-- Poda o excesso de ligas habilitadas (ex: 1.233 de uma vez, via o antigo
-- "Habilitar todas") pra sobrar só as ~100 principais do mundo — mesmo
-- critério usado agora em trackTopLeagues. Isso libera a fila do cron
-- imediatamente, sem precisar esperar dias pra cobrir o backlog.
delete from public.tracked_leagues
where not (
  league_name ilike '%premier league%' or league_name ilike '%la liga%'
  or league_name ilike '%serie a%' or league_name ilike '%bundesliga%'
  or league_name ilike '%ligue 1%' or league_name ilike '%primeira liga%'
  or league_name ilike '%eredivisie%' or league_name ilike '%pro league%'
  or league_name ilike '%premiership%' or league_name ilike '%süper lig%'
  or league_name ilike '%super lig%' or league_name ilike '%super league%'
  or league_name ilike '%superliga%' or league_name ilike '%allsvenskan%'
  or league_name ilike '%eliteserien%' or league_name ilike '%ekstraklasa%'
  or league_name ilike '%fortuna liga%' or league_name ilike '%hnl%'
  or league_name ilike '%super liga%' or league_name ilike '%liga i%'
  or league_name ilike '%nb i%' or league_name ilike '%premier liga%'
  or league_name ilike '%championship%' or league_name ilike '%segunda div%'
  or league_name ilike '%serie b%' or league_name ilike '%2. bundesliga%'
  or league_name ilike '%ligue 2%' or league_name ilike '%eerste divisie%'
  or league_name ilike '%fa cup%' or league_name ilike '%copa del rey%'
  or league_name ilike '%coppa italia%' or league_name ilike '%dfb pokal%'
  or league_name ilike '%coupe de france%' or league_name ilike '%efl cup%'
  or league_name ilike '%carabao cup%' or league_name ilike '%brasileir%'
  or league_name ilike '%liga profesional%' or league_name ilike '%primera divis%'
  or league_name ilike '%liga 1%' or league_name ilike '%mls%'
  or league_name ilike '%liga mx%' or league_name ilike '%leagues cup%'
  or league_name ilike '%j1 league%' or league_name ilike '%k league 1%'
  or league_name ilike '%chinese super league%' or league_name ilike '%saudi pro league%'
  or league_name ilike '%stars league%' or league_name ilike '%persian gulf%'
  or league_name ilike '%isl%' or league_name ilike '%a-league%'
  or league_name ilike '%uae league%' or league_name ilike '%egyptian premier league%'
  or league_name ilike '%premier soccer league%' or league_name ilike '%botola%'
  or league_name ilike '%npfl%' or league_name ilike '%copa do brasil%'
  or league_name ilike '%copa argentina%' or league_name ilike '%champions league%'
  or league_name ilike '%europa league%' or league_name ilike '%conference league%'
  or league_name ilike '%libertadores%' or league_name ilike '%sudamericana%'
  or league_name ilike '%concacaf champions%' or league_name ilike '%afc champions%'
  or league_name ilike '%caf champions league%' or league_name ilike '%world cup%'
  or league_name ilike '%nations league%' or league_name ilike '%euro championship%'
  or league_name ilike '%copa america%' or league_name ilike '%copa américa%'
  or league_name ilike '%africa cup of nations%' or league_name ilike '%asian cup%'
  or league_name ilike '%gold cup%'
);
