-- Poda de volta pra ~100 ligas de verdade — a primeira tentativa de
-- lista curada usava só o nome (ex: "Premier League"), e nomes genéricos
-- como esse são usados por dezenas de países, fazendo o total inflar pra
-- 387. Agora exige nome E país batendo juntos.
delete from public.tracked_leagues
where not (
  (league_name ilike '%premier league%' and country ilike '%england%')
  or (league_name ilike '%la liga%' and country ilike '%spain%')
  or (league_name ilike '%serie a%' and country ilike '%italy%')
  or (league_name ilike '%bundesliga%' and country ilike '%germany%')
  or (league_name ilike '%ligue 1%' and country ilike '%france%')
  or (league_name ilike '%primeira liga%' and country ilike '%portugal%')
  or (league_name ilike '%eredivisie%' and country ilike '%netherlands%')
  or (league_name ilike '%pro league%' and country ilike '%belgium%')
  or (league_name ilike '%premiership%' and country ilike '%scotland%')
  or ((league_name ilike '%süper lig%' or league_name ilike '%super lig%') and country ilike '%turkey%')
  or ((league_name ilike '%premier league%' or league_name ilike '%premier liga%') and country ilike '%russia%')
  or (league_name ilike '%premier league%' and country ilike '%ukraine%')
  or (league_name ilike '%super league%' and country ilike '%greece%')
  or (league_name ilike '%super league%' and country ilike '%switzerland%')
  or (league_name ilike '%bundesliga%' and country ilike '%austria%')
  or (league_name ilike '%superliga%' and country ilike '%denmark%')
  or (league_name ilike '%allsvenskan%' and country ilike '%sweden%')
  or (league_name ilike '%eliteserien%' and country ilike '%norway%')
  or (league_name ilike '%ekstraklasa%' and country ilike '%poland%')
  or ((league_name ilike '%fortuna liga%' or league_name ilike '%first league%') and country ilike '%czech%')
  or (league_name ilike '%hnl%' and country ilike '%croatia%')
  or (league_name ilike '%super liga%' and country ilike '%serbia%')
  or (league_name ilike '%liga i%' and country ilike '%romania%')
  or (league_name ilike '%nb i%' and country ilike '%hungary%')
  or ((league_name ilike '%ligat ha%' or league_name ilike '%premier league%') and country ilike '%israel%')
  or (league_name ilike '%championship%' and country ilike '%england%')
  or ((league_name ilike '%segunda div%' or league_name ilike '%laliga2%') and country ilike '%spain%')
  or (league_name ilike '%serie b%' and country ilike '%italy%')
  or (league_name ilike '%2. bundesliga%' and country ilike '%germany%')
  or (league_name ilike '%ligue 2%' and country ilike '%france%')
  or (league_name ilike '%eerste divisie%' and country ilike '%netherlands%')
  or (league_name ilike '%fa cup%' and country ilike '%england%')
  or (league_name ilike '%copa del rey%' and country ilike '%spain%')
  or (league_name ilike '%coppa italia%' and country ilike '%italy%')
  or (league_name ilike '%dfb pokal%' and country ilike '%germany%')
  or (league_name ilike '%coupe de france%' and country ilike '%france%')
  or ((league_name ilike '%efl cup%' or league_name ilike '%carabao cup%') and country ilike '%england%')
  or ((league_name ilike '%serie a%' or league_name ilike '%serie b%') and country ilike '%brazil%')
  or ((league_name ilike '%liga profesional%' or league_name ilike '%primera divis%') and country ilike '%argentina%')
  or (league_name ilike '%primera divis%' and country ilike '%uruguay%')
  or (league_name ilike '%primera divis%' and country ilike '%chile%')
  or (league_name ilike '%primera a%' and country ilike '%colombia%')
  or (league_name ilike '%liga 1%' and country ilike '%peru%')
  or (league_name ilike '%serie a%' and country ilike '%ecuador%')
  or (league_name ilike '%primera divis%' and country ilike '%paraguay%')
  or (league_name ilike '%primera divis%' and country ilike '%bolivia%')
  or ((league_name ilike '%liga futve%' or league_name ilike '%primera divis%') and country ilike '%venezuela%')
  or (league_name ilike '%mls%' and country ilike '%usa%')
  or (league_name ilike '%liga mx%' and country ilike '%mexico%')
  or (league_name ilike '%leagues cup%')
  or (league_name ilike '%j1 league%' and country ilike '%japan%')
  or (league_name ilike '%k league 1%' and country ilike '%south korea%')
  or (league_name ilike '%super league%' and country ilike '%china%')
  or (league_name ilike '%pro league%' and country ilike '%saudi%')
  or (league_name ilike '%stars league%' and country ilike '%qatar%')
  or (league_name ilike '%pro league%' and country ilike '%uae%')
  or (league_name ilike '%persian gulf%' and country ilike '%iran%')
  or ((league_name ilike '%isl%' or league_name ilike '%indian super league%') and country ilike '%india%')
  or (league_name ilike '%a-league%' and country ilike '%australia%')
  or (league_name ilike '%premier league%' and country ilike '%egypt%')
  or (league_name ilike '%premier soccer league%' and country ilike '%south africa%')
  or (league_name ilike '%botola%' and country ilike '%morocco%')
  or (league_name ilike '%npfl%' and country ilike '%nigeria%')
  or (league_name ilike '%copa do brasil%' and country ilike '%brazil%')
  or (league_name ilike '%copa argentina%' and country ilike '%argentina%')
  or (league_name ilike '%champions league%')
  or (league_name ilike '%europa league%')
  or (league_name ilike '%conference league%')
  or (league_name ilike '%libertadores%')
  or (league_name ilike '%sudamericana%')
  or (league_name ilike '%concacaf champions%')
  or (league_name ilike '%afc champions%')
  or (league_name ilike '%caf champions league%')
  or (league_name ilike '%world cup%')
  or (league_name ilike '%nations league%')
  or (league_name ilike '%euro championship%')
  or (league_name ilike '%copa america%') or (league_name ilike '%copa américa%')
  or (league_name ilike '%africa cup of nations%')
  or (league_name ilike '%asian cup%')
  or (league_name ilike '%gold cup%')
);
